name: character_squared
description: "A Movie and TV Show Tracker App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.6
  flutter_acrylic: ^1.1.4
  fluent_ui: ^4.12.0
  go_router: ^16.2.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  fluent_window: ^0.1.9
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^6.0.0
  tmdb_api: ^2.2.3
  tmdb_api_kit: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/